name: Deploy Frontend to Vercel

on:
  push:
    paths:
      - 'frontend/**'  # Only trigger for changes in the `frontend` folder
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout Code
      - name: Checkout Code
        uses: actions/checkout@v3

      # Step 2: Install Dependencies
      - name: Install Dependencies
        run: |
          cd frontend
          npm ci

      # Step 3: Build Frontend
      - name: Build Frontend
        run: |
          cd frontend
          npm run build

      # Step 4: Deploy to Vercel
      - name: Deploy to Vercel
        env:
          VERCEL_TOKEN: ${{ secrets.VERCEL_TOKEN }}
        run: |
          cd frontend
          npx vercel deploy --prod --token $VERCEL_TOKEN
